path:
  detect_model: models/ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite
  recog_model:
  labels:

stream:
- rtsp://192.168.200.80:555/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
- rtsp://192.168.200.78:556/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream

url: http://htv.ai.dfm-engineering.com/api/v1/admin/public/uplink
