path:
  detect_model: models/ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite
  recog_model:
  labels:

stream:
  out: rtsp://192.168.200.80:555/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
  in: rtsp://192.168.200.78:556/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream

url:
  capture: http://htv.ai.dfm-engineering.com/api/v1/admin/public/uplink
  status: http://htv.ai.dfm-engineering.com/api/v1/admin/public/device-info

model_setting:
  min_face_HD: 64
  min_face_FHD: 96
  threshold: 0.3

oper:
  max_temp: 60
  time_check_temp: 60
  sleep: 5
  mode: 0
  frame_per_capture: 1
