source:
  src: cam
  vid_path: test/test.m4v

path:
  detect_model: models/ssd_mobilenet_v2_face_quant_postprocess_edgetpu.tflite
  # detect_model: models/detection_toco_1_edgetpu(1).tflite
  # recog_model: models/mobilenet_recog_quantized_edgetpu.tflite
  # recog_model: models/model_quant_edgetpu.tflite
  recog_model: models/model_quant_edgetpu.tflite
  labels: models/labels.pbtxt

stream:
  out: rtsp://192.168.200.80:555/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
  # in: rtsp://192.168.200.78:556/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream
  in: rtsp://192.168.200.79:554/user=admin_password=tlJwpbo6_channel=1_stream=0.sdp?real_stream

url:
  capture: http://htv.ai.dfm-engineering.com/api/v1/admin/public/uplink
  status: http://htv.ai.dfm-engineering.com/api/v1/admin/public/device-info

model_setting:
  min_face_HD: 72
  min_face_FHD: 96
  threshold: 0.3
  face_size: 112

tracker:
  min_dist:
    in: 10
    out: 10
  min_appear:
    in: 3
    out: 3
  max_disappear:
    in: 8
    out: 8

oper:
  skip_frame: 3
  max_temp: 60
  time_check_temp: 20
  overheated_sleep: 5
  display: 1
  max_item: 10
  max_img_stack: 10
