item {
  id: 0
  name: 'ANH_NQ'
}
item {
  id: 1
  name: 'BIEN_NT'
}
item {
  id: 2
  name: 'BINH_HH'
}
item {
  id: 3
  name: 'CHAU_VM'
}
item {
  id: 4
  name: 'CHIEN_NN'
}
item {
  id: 5
  name: 'CHI_PH'
}
item {
  id: 6
  name: 'CONG_NH'
}
item {
  id: 7
  name: 'CUONG_TM'
}
item {
  id: 8
  name: 'CUONG_TNM'
}
item {
  id: 9
  name: 'CUONG_VV'
}
item {
  id: 10
  name: 'DAT_HT'
}
item {
  id: 11
  name: 'DOAN_NV'
}
item {
  id: 12
  name: 'DUC_TQ'
}
item {
  id: 13
  name: 'DUNG_LQ'
}
item {
  id: 14
  name: 'HAI_LH'
}
item {
  id: 15
  name: 'HAO_NV'
}
item {
  id: 16
  name: 'HEN_LV'
}
item {
  id: 17
  name: 'HIEN_NN'
}
item {
  id: 18
  name: 'HIEU_TTN'
}
item {
  id: 19
  name: 'HO_VM'
}
item {
  id: 20
  name: 'HUY_HX'
}
item {
  id: 21
  name: 'HUY_NHH'
}
item {
  id: 22
  name: 'HUY_THQ'
}
item {
  id: 23
  name: 'KHAI_DQ'
}
item {
  id: 24
  name: 'KHANH_DQ'
}
item {
  id: 25
  name: 'LINH_LTN'
}
item {
  id: 26
  name: 'LINH_NV'
}
item {
  id: 27
  name: 'LOC_VV'
}
item {
  id: 28
  name: 'LOI_NC'
}
item {
  id: 29
  name: 'MANH_HD'
}
item {
  id: 30
  name: 'MAN_NG'
}
item {
  id: 31
  name: 'MINH_HNT'
}
item {
  id: 32
  name: 'MINH_PN'
}
item {
  id: 33
  name: 'NGAN_NTH'
}
item {
  id: 34
  name: 'NGA_TT'
}
item {
  id: 35
  name: 'NHAN_TT'
}
item {
  id: 36
  name: 'NHU_PT'
}
item {
  id: 37
  name: 'NHU_PTT'
}
item {
  id: 38
  name: 'PHAT_DT'
}
item {
  id: 39
  name: 'PHAT_HT'
}
item {
  id: 40
  name: 'PHUC_LN'
}
item {
  id: 41
  name: 'QUI_PP'
}
item {
  id: 42
  name: 'QUYEN_LT'
}
item {
  id: 43
  name: 'TAN_NMN'
}
item {
  id: 44
  name: 'THANH_HP'
}
item {
  id: 45
  name: 'THANH_LT'
}
item {
  id: 46
  name: 'THIEN_HM'
}
item {
  id: 47
  name: 'THI_PTH'
}
item {
  id: 48
  name: 'THUAN_LV'
}
item {
  id: 49
  name: 'THUY_NX'
}
item {
  id: 50
  name: 'TIN_PK'
}
item {
  id: 51
  name: 'TOAI_HT'
}
item {
  id: 52
  name: 'TOAN_HVA'
}
item {
  id: 53
  name: 'TRANG_VT'
}
item {
  id: 54
  name: 'TRIEU_NB'
}
item {
  id: 55
  name: 'TRUNG_NVB'
}
item {
  id: 56
  name: 'TRUONG_DD'
}
item {
  id: 57
  name: 'TRUONG_LV'
}
item {
  id: 58
  name: 'TUNG_PT'
}
item {
  id: 59
  name: 'VIET_HH'
}
item {
  id: 60
  name: 'VIET_PH'
}
item {
  id: 61
  name: 'VUONG_PM'
}
item {
  id: 62
  name: 'VU_TH'
}
item {
  id: 63
  name: 'VY_TV'
}
